import time

from framework.basic import CkbTest
from framework.test_fiber import Fiber, FiberConfigPath
from framework.util import generate_random_preimage


class TestFiber(CkbTest):

    def test_03(self):
        account = self.Ckb_cli.util_key_info_by_private_key(
            self.Config.ACCOUNT_PRIVATE_1
        )

        # start 2 fiber with xudt
        self.fiber1 = Fiber.init_by_port(
            FiberConfigPath.V100,
            self.Config.ACCOUNT_PRIVATE_1,
            "fiber/node1",
            "8228",
            "8227",
        )
        self.fiber2 = Fiber.init_by_port(
            FiberConfigPath.V100,
            self.Config.ACCOUNT_PRIVATE_2,
            "fiber/node2",
            "8229",
            "8230",
        )

        self.fiber1.get_client().graph_nodes()
        self.fiber2.get_client().graph_nodes()
        self.fiber1.get_client().graph_channels()
        self.fiber2.get_client().graph_channels()

    def test_02(self):
        account = self.Ckb_cli.util_key_info_by_private_key(
            self.Config.ACCOUNT_PRIVATE_1
        )

        # start 2 fiber with xudt
        self.fiber1 = Fiber.init_by_port(
            FiberConfigPath.V100,
            self.Config.ACCOUNT_PRIVATE_1,
            "fiber/node1",
            "8228",
            "8227",
        )
        self.fiber2 = Fiber.init_by_port(
            FiberConfigPath.V100,
            self.Config.ACCOUNT_PRIVATE_2,
            "fiber/node2",
            "8229",
            "8230",
        )
        self.fiber1.prepare()
        self.fiber1.start()
        self.fiber2.prepare()
        self.fiber2.start()
        # connect  2 fiber
        self.fiber1.connect_peer(self.fiber2)

        # open channel
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(1000 * 100000000),
                "public": True,
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )
        wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(), "CHANNEL_READY", 120
        )
        # transfer
        self.fiber1.get_client().graph_channels()
        self.fiber1.get_client().graph_nodes()
        payment_preimage = generate_random_preimage()
        invoice_balance = 100 * 100000000
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": "Fibb",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        time.sleep(10)
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]

        # shut down
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": {
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type",
                    "args": account["lock_arg"],
                },
                "fee_rate": "0x3FC",
            }
        )


def wait_for_channel_state(client, peer_id, expected_state, timeout=120):
    """Wait for a channel to reach a specific state."""
    for _ in range(timeout):
        channels = client.list_channels({"peer_id": peer_id})
        if channels["channels"][0]["state"]["state_name"] == expected_state:
            print(f"Channel reached expected state: {expected_state}")
            return channels["channels"][0]["channel_id"]
        print(
            f"Waiting for channel state: {expected_state}, current state: {channels['channels'][0]['state']['state_name']}"
        )
        time.sleep(1)
    raise TimeoutError(
        f"Channel did not reach state {expected_state} within timeout period."
    )
