# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: fiber debug test
on:
  push:
    branches: ["fiber"]
  pull_request:
    branches: ["fiber"]

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run make prepare
        run: make prepare

      - name: Backup data
        uses: actions/upload-artifact@v4
        with:
          name: prepare-backup-${{ runner.os }}
          path: |
            download/
            source/ckb-cli
            source/ckb-clickb-cli-old

  fiber_test_1:
    needs: prepare
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download prepare backup
        uses: actions/download-artifact@v4
        with:
          name: prepare-backup-${{ runner.os }}
          path: ./

      - name: Run fiber_test_demo
        run: make fiber_test_demo FIBER_TEST_DEMO=test_cases/fiber/devnet/new_invoice

      - name: Publish reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jfoa-test1-reports-${{ runner.os }}
          path: ./report


